//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.23 at 04:18:00 PM TRT 
//


package https.soap_stocks_up_railway;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Stock complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Stock"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stockSymbol" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="latestPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="dailyChangePct" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="dailyChangeInTL" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tradingVolumeTL" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tradeVolumeCount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Stock", propOrder = {
    "stockSymbol",
    "latestPrice",
    "dailyChangePct",
    "dailyChangeInTL",
    "tradingVolumeTL",
    "tradeVolumeCount"
})
public class Stock {

    @XmlElement(required = true)
    protected String stockSymbol;
    @XmlElement(required = true)
    protected BigDecimal latestPrice;
    @XmlElement(required = true)
    protected BigDecimal dailyChangePct;
    @XmlElement(required = true)
    protected BigDecimal dailyChangeInTL;
    @XmlElement(required = true)
    protected BigDecimal tradingVolumeTL;
    @XmlElement(required = true)
    protected BigDecimal tradeVolumeCount;

    /**
     * Gets the value of the stockSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockSymbol() {
        return stockSymbol;
    }

    /**
     * Sets the value of the stockSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockSymbol(String value) {
        this.stockSymbol = value;
    }

    /**
     * Gets the value of the latestPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLatestPrice() {
        return latestPrice;
    }

    /**
     * Sets the value of the latestPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLatestPrice(BigDecimal value) {
        this.latestPrice = value;
    }

    /**
     * Gets the value of the dailyChangePct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDailyChangePct() {
        return dailyChangePct;
    }

    /**
     * Sets the value of the dailyChangePct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDailyChangePct(BigDecimal value) {
        this.dailyChangePct = value;
    }

    /**
     * Gets the value of the dailyChangeInTL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDailyChangeInTL() {
        return dailyChangeInTL;
    }

    /**
     * Sets the value of the dailyChangeInTL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDailyChangeInTL(BigDecimal value) {
        this.dailyChangeInTL = value;
    }

    /**
     * Gets the value of the tradingVolumeTL property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTradingVolumeTL() {
        return tradingVolumeTL;
    }

    /**
     * Sets the value of the tradingVolumeTL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTradingVolumeTL(BigDecimal value) {
        this.tradingVolumeTL = value;
    }

    /**
     * Gets the value of the tradeVolumeCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTradeVolumeCount() {
        return tradeVolumeCount;
    }

    /**
     * Sets the value of the tradeVolumeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTradeVolumeCount(BigDecimal value) {
        this.tradeVolumeCount = value;
    }

}
